# Generated by Django 3.2.6 on 2021-08-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineclass', '0004_auto_20210818_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='helper_csv',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='helper',
            name='helper_audio',
            field=models.FileField(upload_to=''),
        ),
    ]
