# Generated by Django 3.2.6 on 2021-08-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineclass', '0005_auto_20210819_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='helper_txt',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
